import { PipelineStageInfo } from "@/types";

export const PIPELINE_STAGES: PipelineStageInfo[] = [
  {
    id: "ingestion",
    stageNumber: 1,
    title: "Contract Ingestion & Normalization",
    shortName: "Ingestion",
    description: "Parses, dereferences, and validates baseline vs candidate OpenAPI 3.x / Swagger specifications into an immutable AST tree.",
    techStack: ["OpenAPI Parser", "Rust WASM", "JSON Schema Validator"],
    status: "idle",
  },
  {
    id: "diff_engine",
    stageNumber: 2,
    title: "Semantic Spec Diffing",
    shortName: "Diff Engine",
    description: "Calculates structural, type, and constraint deltas across endpoints, parameters, request bodies, and response payloads.",
    techStack: ["Tree Diff Algo", "Semantic Graph", "AST Comparison"],
    status: "idle",
  },
  {
    id: "traffic_replay",
    stageNumber: 3,
    title: "Shadow Traffic Replay",
    shortName: "Traffic Replay",
    description: "Replays sanitized production traffic snippets against candidate environments in real time without impacting live users.",
    techStack: ["eBPF Probe", "Envoy Mirror", "Payload Sanitizer"],
    status: "idle",
  },
  {
    id: "classification",
    stageNumber: 4,
    title: "Compatibility Classification",
    shortName: "Classification",
    description: "Classifies changes into non-breaking additions, safe deprecations, potential breaking schema tweaks, and critical breaking regressions.",
    techStack: ["Rule Evaluator", "ML Classifier", "Behavioral Sandbox"],
    status: "idle",
  },
  {
    id: "impact_analysis",
    stageNumber: 5,
    title: "Downstream Impact Analysis",
    shortName: "Impact Analysis",
    description: "Traces affected downstream microservices, mobile apps, and third-party API clients mapped against consumer usage metrics.",
    techStack: ["Graph Database", "Dependency Mapper", "Telemetry Sync"],
    status: "idle",
  },
  {
    id: "report_generation",
    stageNumber: 6,
    title: "Actionable Report Generation",
    shortName: "Report Generation",
    description: "Generates high-precision engineering reports, PR inline annotations, Slack alerts, and automated rollback triggers.",
    techStack: ["GitHub Checks API", "Markdown Generator", "Webhook Engine"],
    status: "idle",
  },
];
